name: guidedcapstone
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy=1.24.*
  - scipy=1.10.*
  - scikit-learn=1.2.*
  - pandas=1.5.*
  - matplotlib=3.7.*
  - seaborn=0.12.*
  - jupyter
  - jupyterlab